spring:
  application:
    name: console-parcels
  jpa:
    open-in-view: false
  datasource:
    driver-class-name: org.postgresql.Driver

  swagger:
    url:
      path: /

springdoc:
  api-docs:
    enabled: true
    path: /swagger/v3/api-docs
  swagger-ui:
    enabled: true
    path: /swagger-ui.html


billing:
  loadPricing: 50
  unloadPricing: 80
  truckPricing: 200
  filePath: "billing_records.json"

server:
  port: 8080

management:
  endpoint:
    prometheus.enabled: true
    metrics.enabled: true
  endpoints.web:
    base-path: /
    path-mapping:
      prometheus: metrics
    exposure.include: [ 'prometheus', 'health', 'info', 'caches', 'loggers']
  prometheus.metrics.export.enabled: true

common-delivery:
  environment: dev

logging.level:
  com.hofftech.deliverysystem: DEBUG





