spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/delivery_db
    username: delivery_user
    password: delivery_password
    driver-class-name: org.postgresql.Driver

  swagger:
    url:
      path: /

springdoc:
  api-docs:
    enabled: true
    path: /swagger/v3/api-docs
  swagger-ui:
    enabled: true
    path: /swagger-ui.html

telegram:
  token: "7546831359:AAGeR2TeS_j-bJ-BcMMff8QAXcz-cRWxinM"
  username: "DeliveryParcelsBot"

billing:
  loadPricing: 50
  unloadPricing: 80
  truckPricing: 200
  filePath: "billing_records.json"

server:
  port: 8080

management:
  endpoint:
    prometheus.enabled: true
    metrics.enabled: true
  endpoints.web:
    base-path: /
    path-mapping:
      prometheus: metrics
    exposure.include: [ 'prometheus', 'health', 'info', 'caches', 'loggers']
  prometheus.metrics.export.enabled: true

common-delivery:
  environment: dev

logging.level:
  com.hofftech.deliverysystem: DEBUG