spring:
  application:
    name: console-parcels
  jpa:
    open-in-view: false
  datasource:
    url: jdbc:postgresql://localhost:5432/delivery_db
    username: delivery_user
    password: delivery_password
    driver-class-name: org.postgresql.Driver
  kafka:
    consumer:
      bootstrap-servers: localhost:29092
swagger:
  url:
    path: /

springdoc:
  api-docs:
    enabled: true
    path: /swagger/v3/api-docs
  swagger-ui:
    enabled: true
    path: /swagger-ui.html

schedule:
  process-outbox-messages:
    interval: 1000

billing:
  loadPricing: 50
  unloadPricing: 80
  truckPricing: 200
  filePath: "billing_records.json"

server:
  port: 8080

management:
  endpoint:
    prometheus.enabled: true
    metrics.enabled: true
  endpoints.web:
    base-path: /
    path-mapping:
      prometheus: metrics
    exposure.include: [ 'prometheus', 'health', 'info', 'caches', 'loggers']
  prometheus.metrics.export.enabled: true

common-delivery:
  environment: dev

logging.level:
  com.hofftech.deliverysystem: DEBUG





