version: '3.8'

services:
  app:
    image: openjdk:21-jdk-slim
    container_name: delivery-system-app
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/delivery_db
      SPRING_DATASOURCE_USERNAME: delivery_user
      SPRING_DATASOURCE_PASSWORD: delivery_password
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      SPRING_PROFILES_ACTIVE: dev
    depends_on:
      - db
    ports:
      - "8080:8080"

  db:
    image: postgres:15
    container_name: delivery-system-db
    environment:
      POSTGRES_DB: delivery_db
      POSTGRES_USER: delivery_user
      POSTGRES_PASSWORD: delivery_password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
